# Site settings
title: RomSec
header-img: img/index-header-two.JPG
email: romsec@protonmail.com
copyright_name: RomSec
description: "Here"
baseurl: ""
url: "http://romcybersec.com"
twitter_username: r0msec
github_username:  romsec
email_username:  romsec@protonmail.com
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
